### ISSUE TITLE
How is this project licensed?

### ISSUE THREAD

**Issue by basilhussain** [mikechambers84/STM8-Emulator#6]
What kind of open source license is this project under? There is no mention of licensing terms in the readme, nor in any code comments, etc.

**Comment by mikechambers84** [comment]
Yes, it does need a license. I will fix this ASAP. Probably GPLv3, though I'm considering MIT.

**Comment by mikechambers84** [comment]
Basil, I've added a LICENSE file. It's GPLv3.
